-- MySQL Script generated by MySQL Workbench
-- Sun Nov 24 17:57:25 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema restaurant
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `restaurant` ;

-- -----------------------------------------------------
-- Schema restaurant
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurant` DEFAULT CHARACTER SET utf8 ;
USE `restaurant` ;

-- -----------------------------------------------------
-- Table `restaurant`.`order_tab`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`order_tab` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `total` INT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`menu_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`menu_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `price` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`order_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` INT NULL,
  `cost` INT NULL,
  `menu_item_id` INT NOT NULL,
  `order_tab_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_item_menu_item_idx` (`menu_item_id` ASC) VISIBLE,
  INDEX `fk_order_item_order_tab1_idx` (`order_tab_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_item_menu_item`
    FOREIGN KEY (`menu_item_id`)
    REFERENCES `restaurant`.`menu_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_item_order_tab1`
    FOREIGN KEY (`order_tab_id`)
    REFERENCES `restaurant`.`order_tab` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
