-- MySQL Script generated by MySQL Workbench
-- Fri Nov 15 15:06:38 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema restaurant
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `restaurant` ;

-- -----------------------------------------------------
-- Schema restaurant
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurant` DEFAULT CHARACTER SET utf8 ;
USE `restaurant` ;

-- -----------------------------------------------------
-- Table `restaurant`.`OrderTab`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`OrderTab` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `total_price` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`MenuItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`MenuItem` (
  `id` INT NOT NULL,
  `price` INT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`OrderItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`OrderItem` (
  `id` INT NOT NULL,
  `MenuItem_id` INT NOT NULL,
  `Order_id` INT NOT NULL,
  `amount` INT NULL,
  `price` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_OrderItem_MenuItem1_idx` (`MenuItem_id` ASC) VISIBLE,
  INDEX `fk_OrderItem_Order1_idx` (`Order_id` ASC) VISIBLE,
  CONSTRAINT `fk_OrderItem_MenuItem1`
    FOREIGN KEY (`MenuItem_id`)
    REFERENCES `restaurant`.`MenuItem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderItem_Order1`
    FOREIGN KEY (`Order_id`)
    REFERENCES `restaurant`.`OrderTab` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
